spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis
  data:
    redis:
      port: 6380
      host: 192.168.157.137
      database: 0

mybatis-plus:
  type-aliases-package: com.jy.entity
  mapper-locations: classpath:com/jy/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    cache-enabled: true

logging:
  level:
    com.jy.mapper: debug
